name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
          submodules: recursive
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: build
      run: make
    - name: sigle-thread-test
      run: make test-normal
    - name: multy-thread-test
      run: make test-mt
    - name: cpp-ptimization-test
      run: make test-cpp
